MODULE CALCULUS_MODULE
	IMPLICIT NONE
	
	INTERFACE
		REAL(8) MODULE FUNCTION TRAPEZOIDAL_INTEGRAL(VAL_ARR, &
													 NUMB, &
													 DX)
			IMPLICIT NONE
			REAL(8), DIMENSION(:), INTENT(IN)	::	VAL_ARR
			INTEGER(4), INTENT(IN)				::	NUMB
			REAL(8), INTENT(IN)					::	DX
		END FUNCTION TRAPEZOIDAL_INTEGRAL
		
	END INTERFACE
END MODULE CALCULUS_MODULE