SUBMODULE (CALCULUS_MODULE) CALCULUS_INTEGRAL
	CONTAINS
		REAL(8) MODULE FUNCTION TRAPEZOIDAL_INTEGRAL(VAL_ARR, &
													 NUMB, &
													 DX)
			IMPLICIT NONE
			REAL(8), DIMENSION(:), INTENT(IN)	::	VAL_ARR
			INTEGER(4), INTENT(IN)				::	NUMB
			REAL(8), INTENT(IN)					::	DX
			INTEGER(4)							::	I
			
			TRAPEZOIDAL_INTEGRAL = (VAL_ARR(1) + VAL_ARR(NUMB)) * 0.5
			DO I = 2, NUMB - 1, 1
				TRAPEZOIDAL_INTEGRAL = TRAPEZOIDAL_INTEGRAL + VAL_ARR(I)
			ENDDO
			TRAPEZOIDAL_INTEGRAL = TRAPEZOIDAL_INTEGRAL * DX
			
		END FUNCTION TRAPEZOIDAL_INTEGRAL
		
END SUBMODULE CALCULUS_INTEGRAL