MODULE GRID_MODULE
	IMPLICIT NONE
	
	INTERFACE
	
		REAL(8) MODULE FUNCTION CREATE_DIM1(	NODE_ARR_XI, &
												CELL_ARR_XI, &
												START_XI, &
												END_XI, &
												NUMB_XI)
			IMPLICIT NONE
			REAL(8), DIMENSION(:), INTENT(OUT) 	:: 	NODE_ARR_XI, &
													CELL_ARR_XI
			INTEGER(4), INTENT(IN) 				:: 	NUMB_XI
			REAL(8), INTENT(IN) 				:: 	START_XI, &
													END_XI
			
		END FUNCTION CREATE_DIM1
		
		REAL(8) MODULE FUNCTION CREATE_DIM2(	NODE_ARR_XI, &
												START_XI, &
												END_XI, &
												NUMB_XI)
			IMPLICIT NONE
			REAL(8), DIMENSION(:), INTENT(OUT) 	:: 	NODE_ARR_XI
			INTEGER(4), INTENT(IN) 				:: 	NUMB_XI
			REAL(8), INTENT(IN) 				:: 	START_XI, &
													END_XI
			
		END FUNCTION CREATE_DIM2
													
	END INTERFACE
	
	INTERFACE CREATE_DIM
		MODULE PROCEDURE CREATE_DIM1, CREATE_DIM2
	END INTERFACE CREATE_DIM
	
END MODULE GRID_MODULE